### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by Dv04** [Dv04/Text_Detector#17]
### Description:
Modularize the code to improve readability, maintainability, and scalability.

### Tasks:
- Break down monolithic code files into smaller, manageable modules.
- Ensure functions and classes adhere to the Single Responsibility Principle.
- Update function and variable names to be descriptive and adhere to naming conventions. (wherever needed)
- Organize the directory structure for better navigation and understanding.
- Ensure that there is a clear and consistent coding style throughout the project.
- Add comments and documentation where necessary to explain complex or non-intuitive code.

### Note:
* A PR can be generated if at least one task from above is completed

**Comment by ChiragAgg5k** [comment]
Hey, I can work on this issue. Can you assign it to me?

**Comment by Dv04** [comment]
@ChiragAgg5k sure. Glad to have you with us. 

As this is a multi task issue, rather than assigning, please submit a PR after October 1st and we will accept it. It will count towards your goal. Just tag the PR correctly with this issue.

If you still want to get assigned comment below and I will assign it to you.

**Comment by ChiragAgg5k** [comment]
Got it. I will start working on it soon and submit the PR 👍
