### ISSUE TITLE
Create Comprehensive README.md

### ISSUE THREAD

**Issue by Dv04** [Dv04/Text_Detector#9]
### Description:
The repository lacks a detailed `README.md` file. A well-structured and informative README is crucial for understanding the project, its structure, and how to use or contribute to it.

### Tasks:
- Provide a project description explaining the purpose and functionality of Text_Detector.
- Include setup instructions detailing how to get the project running.
- Document usage examples with code snippets and screenshots if possible.
- List dependencies and provide information on how to install them.
- Add a section for contributors on how to report issues, propose changes or contribute to the project.
- Include a license and citation information if applicable.

**Comment by harshita1611** [comment]
I woul be happy to work on this issue. Can you please assign it to me?

**Comment by Dv04** [comment]
Hey @harshita1611, glad to have you with us. 

Assigning you now.

**Comment by harshita1611** [comment]
Alright, thank you
